!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  1: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  2: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  3: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  4: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  5: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  6: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  7: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  8: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  9: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  10: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  11: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  12: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  13: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  14: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
  15: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
