!ArenaConfig
arenas:
  0: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  1: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  2: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  3: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  4: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  5: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  6: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  7: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  8: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  9: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  10: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  11: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  12: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  13: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  14: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  15: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
