!ArenaConfig
arenas:
  0: !Arena
    t: 0
    blackouts: [-20]
    items:
    - !Item
      name: GoodGoal
  1: !Arena
    t: 100
    blackouts: [-40]
    items:
    - !Item
      name: Wall
    - !Item
      name: GoodGoal
  2: !Arena
    t: 100
    blackouts: [50, 55, 75, 80, 100, 105, 125]
    items:
    - !Item
      name: WallTranparent
    - !Item
      name: GoodGoal
  3: !Arena
    t: 100
    blackouts: [25, 30, 50, 55, 75]
    items:
    - !Item
      name: CylinderTunnel
    - !Item
      name: GoodGoal
  4: !Arena
    t: 0
    blackouts: [-20]
    items:
    - !Item
      name: GoodGoal
  5: !Arena
    t: 100
    blackouts: [-40]
    items:
    - !Item
      name: Wall
    - !Item
      name: GoodGoal
  6: !Arena
    t: 100
    blackouts: [50, 55, 75, 80, 100, 105, 125]
    items:
    - !Item
      name: WallTranparent
    - !Item
      name: GoodGoal
  7: !Arena
    t: 100
    blackouts: [25, 30, 50, 55, 75]
    items:
    - !Item
      name: CylinderTunnel
    - !Item
      name: GoodGoal
  8: !Arena
    t: 0
    blackouts: [-20]
    items:
    - !Item
      name: GoodGoal
  9: !Arena
    t: 100
    blackouts: [-40]
    items:
    - !Item
      name: Wall
    - !Item
      name: GoodGoal
  10: !Arena
    t: 100
    blackouts: [50, 55, 75, 80, 100, 105, 125]
    items:
    - !Item
      name: WallTranparent
    - !Item
      name: GoodGoal
  11: !Arena
    t: 100
    blackouts: [25, 30, 50, 55, 75]
    items:
    - !Item
      name: CylinderTunnel
    - !Item
      name: GoodGoal
  12: !Arena
    t: 0
    blackouts: [-20]
    items:
    - !Item
      name: GoodGoal
  13: !Arena
    t: 100
    blackouts: [-40]
    items:
    - !Item
      name: Wall
    - !Item
      name: GoodGoal
  14: !Arena
    t: 100
    blackouts: [50, 55, 75, 80, 100, 105, 125]
    items:
    - !Item
      name: WallTranparent
    - !Item
      name: GoodGoal
  15: !Arena
    t: 100
    blackouts: [25, 30, 50, 55, 75]
    items:
    - !Item
      name: CylinderTunnel
    - !Item
      name: GoodGoal
