!ArenaConfig
arenas:
  0: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  1: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  2: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  3: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  4: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  5: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  6: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  7: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  8: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  9: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  10: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  11: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  12: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  13: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  14: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  15: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  16: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  17: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  18: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  19: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  20: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  21: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  22: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  23: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  24: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  25: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  26: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  27: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  28: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  29: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  30: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  31: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
