!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  1: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  2: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  3: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  4: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  5: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  6: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  7: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  8: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  9: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  10: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  11: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  12: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  13: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  14: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  15: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  16: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  17: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  18: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  19: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  20: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  21: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  22: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  23: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  24: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  25: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  26: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  27: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  28: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  29: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  30: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
  31: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
