!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  1: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  2: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  3: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  4: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  5: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  6: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  7: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  8: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  9: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodBounceGoalMulti
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  10: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  11: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  12: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodBounceGoalMulti
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  13: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  14: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  15: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodBounceGoalMulti
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  16: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  17: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  18: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodBounceGoalMulti
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  19: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  20: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  21: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodBounceGoalMulti
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  22: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  23: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  24: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodBounceGoalMulti
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  25: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  26: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  27: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodBounceGoalMulti
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  28: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  29: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  30: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodBounceGoalMulti
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
  31: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
