!ArenaConfig
arenas:
  0: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  1: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  2: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  3: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  4: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  5: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  6: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  7: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  8: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  9: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  10: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  11: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  12: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  13: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  14: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  15: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  16: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  17: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  18: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  19: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  20: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  21: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  22: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  23: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  24: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  25: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  26: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  27: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  28: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  29: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  30: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  31: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: HotZone
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
    - !Item
      name: CylinderTunnelTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
